[tool.poetry]
name = "sendtokindle"
version = "0.1.0"
description = "Python library for sending books to kindle over http"
authors = ["Max Johnson <mjohnson@plaid.com>"]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
